In [ ]:
import subprocess, os, sys

GITHUB_USER  = "YusrahS"
GITHUB_REPO  = "Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"
GITHUB_TOKEN = "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"
repo_path    = f"/content/{GITHUB_REPO}"

if not os.path.exists(repo_path):
    subprocess.run(
        f"git clone https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git",
        shell=True, cwd="/content"
    )
    print("✅ Repo cloned")

sys.path.insert(0, repo_path)
os.chdir(repo_path)
print(f"✅ Ready! Working directory: {os.getcwd()}")

✅ Repo cloned
✅ Ready! Working directory: /content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')


import os
repo_url = "https://github.com/YusrahS/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"
repo_name = "Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"

if not os.path.exists(f'/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-'):
    !cd /content/drive/MyDrive/ && git clone https://github.com/YusrahS/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
    print("✅ Repository cloned to Google Drive")
else:
    !cd /content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study- && git pull
    print("✅ Repository updated in Google Drive")

!rm -f /content/content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
!ln -sf /content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study- /content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
%cd /content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-

!git config --global user.email "yusrahsumtally220301@gmail.com"
!git config --global user.name "YusrahS"

print(f"Current directory: {os.getcwd()}")
!ls -la

Mounted at /content/drive
Already up to date.
✅ Repository updated in Google Drive
/content
Current directory: /content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
total 40
drwxr-xr-x 7 root root 4096 Jun 23 20:42 .
drwxr-xr-x 1 root root 4096 Jun 23 20:42 ..
lrwxrwxrwx 1 root root  101 Jun 23 20:42 Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study- -> /content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
drwxr-xr-x 6 root root 4096 Jun 23 20:42 Datasets
drwxr-xr-x 8 root root 4096 Jun 23 20:42 .git
-rw-r--r-- 1 root root   25 Jun 23 20:41 .gitignore
drwxr-xr-x 2 root root 4096 Jun 23 20:42 Notebooks
-rw-r--r-- 1 root root  345 Jun 23 20:42 README.md
drwxr-xr-x 4 root root 4096 Jun 23 20:42 reports
drwxr-xr-x 6 root root 4096 Jun 23 20:42 src

In [ ]:
import os
print(os.listdir('/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data'))

['bilingual_transformer_data.pkl', 'english_transformer_data.pkl', 'spanish_transformer_data.pkl', 'bilingual_bilstm_data.pkl', 'english_bilstm_data.pkl', 'spanish_bilstm_data.pkl', 'models']

In [ ]:
#Imports

# Data handling
import pandas as pd
import numpy as np
import pickle
import os

# Google Drive
from google.colab import drive

# Hugging Face Transformers
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)

# PyTorch (backend for transformers)
import torch
from torch.utils.data import Dataset

# Evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Progress and utilities
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# For cross-lingual re-tokenisation
from src.data.preprocessor import clean_text

Load data

In [ ]:
# loading bilingual transformer data from google drive
# FIX: correct filename (was transformer_data.pkl) + new shared drive path
drive_path = '/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data/bilingual_transformer_data.pkl'

with open(drive_path, 'rb') as f:
    bilingual_data = pickle.load(f)

# Extract data
train_texts = bilingual_data['train_texts']
validation_texts = bilingual_data['val_texts']
test_texts = bilingual_data['test_texts']
train_labels = bilingual_data['train_labels']
validation_labels = bilingual_data['val_labels']
test_labels = bilingual_data['test_labels']
max_len = bilingual_data['max_len']

In [ ]:
# loading english transformer data (for EN->ES cross-lingual training)
drive_path = '/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data/english_transformer_data.pkl'

with open(drive_path, 'rb') as f:
    english_data = pickle.load(f)

english_train_texts = english_data['train_texts']
english_validation_texts = english_data['val_texts']
english_test_texts = english_data['test_texts']
english_train_labels = english_data['train_labels']
english_validation_labels = english_data['val_labels']
english_test_labels = english_data['test_labels']

In [ ]:
# loading spanish transformer data (for ES->EN cross-lingual training)
drive_path = '/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data/spanish_transformer_data.pkl'

with open(drive_path, 'rb') as f:
    spanish_data = pickle.load(f)

spanish_train_texts = spanish_data['train_texts']
spanish_validation_texts = spanish_data['val_texts']
spanish_test_texts = spanish_data['test_texts']
spanish_train_labels = spanish_data['train_labels']
spanish_validation_labels = spanish_data['val_labels']
spanish_test_labels = spanish_data['test_labels']

In [ ]:
# Load bilingual test CSV to get per-language subsets (for per-language breakdown)
bilingual_test_df = pd.read_csv('Datasets/Dataset_splits/bilingual_test.csv')
bilingual_test_df['clean_text'] = bilingual_test_df['text'].apply(clean_text)

en_mask = bilingual_test_df['language'] == 'en'
es_mask = bilingual_test_df['language'] == 'es'

en_test_texts_from_bilingual = bilingual_test_df.loc[en_mask, 'clean_text'].tolist()
es_test_texts_from_bilingual = bilingual_test_df.loc[es_mask, 'clean_text'].tolist()
en_test_labels_from_bilingual = bilingual_test_df.loc[en_mask, 'binary_label'].tolist()
es_test_labels_from_bilingual = bilingual_test_df.loc[es_mask, 'binary_label'].tolist()

print(f"English subset of bilingual test: {len(en_test_texts_from_bilingual)} samples")
print(f"Spanish subset of bilingual test: {len(es_test_texts_from_bilingual)} samples")

English subset of bilingual test: 10876 samples
Spanish subset of bilingual test: 8076 samples

In [ ]:
# Dataset function
class CyberbullyingDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

In [ ]:
#Metrics function
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {
        'accuracy': accuracy_score(labels, predictions),
        'f1': f1_score(labels, predictions, average='macro'),
        'precision': precision_score(labels, predictions, average='macro'),
        'recall': recall_score(labels, predictions, average='macro')
    }

Helper function for evaluating a trained model on any text/label set (used for per-language breakdown and cross-lingual tests)

In [ ]:
def evaluate_on_texts(tokenizer, model, texts, labels, title, batch_size=16):
    """Tokenise texts fresh and evaluate a trained model on them.
    Used for per-language breakdown and cross-lingual evaluation."""
    encodings = tokenizer(texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
    dataset = CyberbullyingDataset(encodings, labels)

    temp_args = TrainingArguments(output_dir='./results/temp_eval', per_device_eval_batch_size=batch_size, report_to='none')
    temp_trainer = Trainer(model=model, args=temp_args, compute_metrics=compute_metrics)

    output = temp_trainer.predict(dataset)
    preds = np.argmax(output.predictions, axis=1)

    acc = accuracy_score(labels, preds)
    prec = precision_score(labels, preds, average='macro')
    rec = recall_score(labels, preds, average='macro')
    f1 = f1_score(labels, preds, average='macro')

    print(f"\n{'='*55}")
    print(f"  {title}")
    print(f"{'='*55}")
    print(f"   Accuracy:  {acc:.4f}")
    print(f"   Precision: {prec:.4f}")
    print(f"   Recall:    {rec:.4f}")
    print(f"   F1-Score:  {f1:.4f}")
    print(classification_report(labels, preds, target_names=['Non-Abusive (0)', 'Abusive (1)']))

    return preds, output.predictions

In [ ]:
#Keep colab alive for training

# Simple clicker to prevent timeout
def keep_alive():
    import time
    from IPython.display import display, Javascript
    display(Javascript("""
        function ClickConnect(){
            console.log("Keeping Colab alive...");
            document.querySelector("colab-connect-button").click()
        }
        setInterval(ClickConnect, 60000)
    """))
    print("✅ Keep-alive enabled - Colab won't disconnect")

keep_alive()

✅ Keep-alive enabled - Colab won't disconnect

XLM-R

In [ ]:
# ==================== XLM-R: Bilingual training ================================

#loading tokenizer
xlmr_tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base')
xlmr_model = AutoModelForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=2)

xlmr_train_encodings = xlmr_tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

xlmr_validation_encodings = xlmr_tokenizer(
    validation_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

xlmr_test_encodings = xlmr_tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

# datasets
xlmr_train_dataset = CyberbullyingDataset(xlmr_train_encodings, train_labels)
xlmr_validation_dataset = CyberbullyingDataset(xlmr_validation_encodings, validation_labels)
xlmr_test_dataset = CyberbullyingDataset(xlmr_test_encodings, test_labels)

# Training arguments
training_args = TrainingArguments(
    output_dir='./results/xlmr',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer = Trainer(
    model=xlmr_model,
    args=training_args,
    train_dataset=xlmr_train_dataset,
    eval_dataset=xlmr_validation_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()
xlmr_test_results = trainer.evaluate(xlmr_test_dataset)
print(xlmr_test_results)

# predictions + probabilities for ensemble
xlmr_predictions = trainer.predict(xlmr_test_dataset)
xlmr_pred_labels = np.argmax(xlmr_predictions.predictions, axis=1)
xlmr_pred_probs = torch.softmax(torch.tensor(xlmr_predictions.predictions), dim=1).numpy()

# Save
xlmr_model.save_pretrained('models_saved/xlmr_model')
xlmr_tokenizer.save_pretrained('models_saved/xlmr_model')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
import shutil, os
drive_models = '/content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data/models'
os.makedirs(drive_models, exist_ok=True)
shutil.copytree('models_saved/xlmr_model', f'{drive_models}/xlmr_model', dirs_exist_ok=True)
print("✅ XLM-R saved to Drive")

In [ ]:
# XLM-R: per-language breakdown on bilingual test set
xlmr_en_preds, _ = evaluate_on_texts(xlmr_tokenizer, xlmr_model, en_test_texts_from_bilingual,
                                       en_test_labels_from_bilingual, "XLM-R — Bilingual test: English subset")
xlmr_es_preds, _ = evaluate_on_texts(xlmr_tokenizer, xlmr_model, es_test_texts_from_bilingual,
                                       es_test_labels_from_bilingual, "XLM-R — Bilingual test: Spanish subset")

In [ ]:
# ==================== XLM-R: EN->ES cross-lingual ================================
# Train a fresh XLM-R on English only, test on Spanish only

xlmr_en_tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base')
xlmr_en_model = AutoModelForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=2)

xlmr_en_train_encodings = xlmr_en_tokenizer(english_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
xlmr_en_val_encodings = xlmr_en_tokenizer(english_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

xlmr_en_train_dataset = CyberbullyingDataset(xlmr_en_train_encodings, english_train_labels)
xlmr_en_val_dataset = CyberbullyingDataset(xlmr_en_val_encodings, english_validation_labels)

training_args_en = TrainingArguments(
    output_dir='./results/xlmr_en',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_en = Trainer(
    model=xlmr_en_model,
    args=training_args_en,
    train_dataset=xlmr_en_train_dataset,
    eval_dataset=xlmr_en_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_en.train()

# Test the EN-trained model on Spanish text
xlmr_en_es_preds, _ = evaluate_on_texts(xlmr_en_tokenizer, xlmr_en_model, spanish_test_texts,
                                          spanish_test_labels, "XLM-R — EN→ES cross-lingual (train EN, test ES)")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

=======================================================
  XLM-R — EN→ES cross-lingual (train EN, test ES)
=======================================================
   Accuracy:  0.5079
   Precision: 0.5119
   Recall:    0.5106
   F1-Score:  0.4950
                 precision    recall  f1-score   support

Non-Abusive (0)       0.50      0.68      0.58      3974
    Abusive (1)       0.52      0.34      0.41      4102

       accuracy                           0.51      8076
      macro avg       0.51      0.51      0.49      8076
   weighted avg       0.51      0.51      0.49      8076

In [ ]:
# ==================== XLM-R: ES->EN cross-lingual ================================
# Train a fresh XLM-R on Spanish only, test on English only

xlmr_es_tokenizer = AutoTokenizer.from_pretrained('xlm-roberta-base')
xlmr_es_model = AutoModelForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=2)

xlmr_es_train_encodings = xlmr_es_tokenizer(spanish_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
xlmr_es_val_encodings = xlmr_es_tokenizer(spanish_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

xlmr_es_train_dataset = CyberbullyingDataset(xlmr_es_train_encodings, spanish_train_labels)
xlmr_es_val_dataset = CyberbullyingDataset(xlmr_es_val_encodings, spanish_validation_labels)

training_args_es = TrainingArguments(
    output_dir='./results/xlmr_es',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_es = Trainer(
    model=xlmr_es_model,
    args=training_args_es,
    train_dataset=xlmr_es_train_dataset,
    eval_dataset=xlmr_es_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_es.train()

# Test the ES-trained model on English text
xlmr_es_en_preds, _ = evaluate_on_texts(xlmr_es_tokenizer, xlmr_es_model, english_test_texts,
                                          english_test_labels, "XLM-R — ES→EN cross-lingual (train ES, test EN)")

mBERT

In [ ]:
# mBERT: Bilingual training
mbert_tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')
mbert_model = AutoModelForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=2)


mbert_train_encodings = mbert_tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

mbert_validation_encodings = mbert_tokenizer(
    validation_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

mbert_test_encodings = mbert_tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

# datasets
mbert_train_dataset = CyberbullyingDataset(mbert_train_encodings, train_labels)
mbert_validation_dataset = CyberbullyingDataset(mbert_validation_encodings, validation_labels)
mbert_test_dataset = CyberbullyingDataset(mbert_test_encodings, test_labels)


# Training arguments
# FIX: eval_strategy (was evaluation_strategy - deprecated key, caused mismatch with other models)
training_args = TrainingArguments(
    output_dir='./results/mbert',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer = Trainer(
    model=mbert_model,
    args=training_args,
    train_dataset=mbert_train_dataset,
    eval_dataset=mbert_validation_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()
mbert_test_results = trainer.evaluate(mbert_test_dataset)
print(mbert_test_results)

# predictions + probabilities for ensemble
mbert_predictions = trainer.predict(mbert_test_dataset)
mbert_pred_labels = np.argmax(mbert_predictions.predictions, axis=1)
mbert_pred_probs = torch.softmax(torch.tensor(mbert_predictions.predictions), dim=1).numpy()

mbert_model.save_pretrained('models_saved/mbert_model')
mbert_tokenizer.save_pretrained('models_saved/mbert_model')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

{'eval_loss': 0.3000534772872925, 'eval_accuracy': 0.902648796960743, 'eval_f1': 0.9021336529211801, 'eval_precision': 0.9030541126899754, 'eval_recall': 0.9015242441365596}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('models_saved/mbert_model/tokenizer_config.json',
 'models_saved/mbert_model/tokenizer.json')

In [ ]:
# mBERT: per-language breakdown on bilingual test set
mbert_en_preds, _ = evaluate_on_texts(mbert_tokenizer, mbert_model, en_test_texts_from_bilingual,
                                        en_test_labels_from_bilingual, "mBERT — Bilingual test: English subset")
mbert_es_preds, _ = evaluate_on_texts(mbert_tokenizer, mbert_model, es_test_texts_from_bilingual,
                                        es_test_labels_from_bilingual, "mBERT — Bilingual test: Spanish subset")

=======================================================
  mBERT — Bilingual test: English subset
=======================================================
   Accuracy:  0.9136
   Precision: 0.9154
   Recall:    0.9105
   F1-Score:  0.9124
                 precision    recall  f1-score   support

Non-Abusive (0)       0.93      0.88      0.90      4938
    Abusive (1)       0.90      0.94      0.92      5938

       accuracy                           0.91     10876
      macro avg       0.92      0.91      0.91     10876
   weighted avg       0.91      0.91      0.91     10876

=======================================================
  mBERT — Bilingual test: Spanish subset
=======================================================
   Accuracy:  0.8879
   Precision: 0.8879
   Recall:    0.8880
   F1-Score:  0.8879
                 precision    recall  f1-score   support

Non-Abusive (0)       0.88      0.89      0.89      3974
    Abusive (1)       0.89      0.89      0.89      4102

       accuracy                           0.89      8076
      macro avg       0.89      0.89      0.89      8076
   weighted avg       0.89      0.89      0.89      8076

In [ ]:
# ==================== mBERT: EN->ES cross-lingual ================================
mbert_en_tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')
mbert_en_model = AutoModelForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=2)

mbert_en_train_encodings = mbert_en_tokenizer(english_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
mbert_en_val_encodings = mbert_en_tokenizer(english_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

mbert_en_train_dataset = CyberbullyingDataset(mbert_en_train_encodings, english_train_labels)
mbert_en_val_dataset = CyberbullyingDataset(mbert_en_val_encodings, english_validation_labels)

training_args_en = TrainingArguments(
    output_dir='./results/mbert_en',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_en = Trainer(
    model=mbert_en_model,
    args=training_args_en,
    train_dataset=mbert_en_train_dataset,
    eval_dataset=mbert_en_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_en.train()

mbert_en_es_preds, _ = evaluate_on_texts(mbert_en_tokenizer, mbert_en_model, spanish_test_texts,
                                           spanish_test_labels, "mBERT — EN→ES cross-lingual (train EN, test ES)")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

=======================================================
  mBERT — EN→ES cross-lingual (train EN, test ES)
=======================================================
   Accuracy:  0.4783
   Precision: 0.4610
   Recall:    0.4845
   F1-Score:  0.3903
                 precision    recall  f1-score   support

Non-Abusive (0)       0.48      0.87      0.62      3974
    Abusive (1)       0.44      0.10      0.16      4102

       accuracy                           0.48      8076
      macro avg       0.46      0.48      0.39      8076
   weighted avg       0.46      0.48      0.39      8076

In [ ]:
# ==================== mBERT: ES->EN cross-lingual ================================
mbert_es_tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')
mbert_es_model = AutoModelForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=2)

mbert_es_train_encodings = mbert_es_tokenizer(spanish_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
mbert_es_val_encodings = mbert_es_tokenizer(spanish_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

mbert_es_train_dataset = CyberbullyingDataset(mbert_es_train_encodings, spanish_train_labels)
mbert_es_val_dataset = CyberbullyingDataset(mbert_es_val_encodings, spanish_validation_labels)

training_args_es = TrainingArguments(
    output_dir='./results/mbert_es',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_es = Trainer(
    model=mbert_es_model,
    args=training_args_es,
    train_dataset=mbert_es_train_dataset,
    eval_dataset=mbert_es_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_es.train()

mbert_es_en_preds, _ = evaluate_on_texts(mbert_es_tokenizer, mbert_es_model, english_test_texts,
                                           english_test_labels, "mBERT — ES→EN cross-lingual (train ES, test EN)")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

=======================================================
  mBERT — ES→EN cross-lingual (train ES, test EN)
=======================================================
   Accuracy:  0.4960
   Precision: 0.4683
   Recall:    0.4747
   F1-Score:  0.4548
                 precision    recall  f1-score   support

Non-Abusive (0)       0.41      0.24      0.31      4938
    Abusive (1)       0.53      0.71      0.60      5938

       accuracy                           0.50     10876
      macro avg       0.47      0.47      0.45     10876
   weighted avg       0.47      0.50      0.47     10876

DistilBERT

In [ ]:
#DistilBERT: Bilingual training
# FIX: distilbert-base-multilingual-cased (was distilbert-base-uncased, English-only -
# the original checkpoint had never seen Spanish during pre-training)
distilbert_tokenizer = AutoTokenizer.from_pretrained('distilbert-base-multilingual-cased')
distilbert_model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-multilingual-cased', num_labels=2)


distilbert_train_encodings = distilbert_tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

distilbert_validation_encodings = distilbert_tokenizer(
    validation_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

distilbert_test_encodings = distilbert_tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128,
    return_tensors='pt'
)

# datasets
distilbert_train_dataset = CyberbullyingDataset(distilbert_train_encodings, train_labels)
distilbert_validation_dataset = CyberbullyingDataset(distilbert_validation_encodings, validation_labels)
distilbert_test_dataset = CyberbullyingDataset(distilbert_test_encodings, test_labels)

# Training arguments
training_args = TrainingArguments(
    output_dir='./results/distilbert',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer = Trainer(
    model=distilbert_model,
    args=training_args,
    train_dataset=distilbert_train_dataset,
    eval_dataset=distilbert_validation_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()
distilbert_test_results = trainer.evaluate(distilbert_test_dataset)
print(distilbert_test_results)

# predictions + probabilities for ensemble
distilbert_predictions = trainer.predict(distilbert_test_dataset)
distilbert_pred_labels = np.argmax(distilbert_predictions.predictions, axis=1)
distilbert_pred_probs = torch.softmax(torch.tensor(distilbert_predictions.predictions), dim=1).numpy()

distilbert_model.save_pretrained('models_saved/distilbert_model')
distilbert_tokenizer.save_pretrained('models_saved/distilbert_model')

#backup to google drive
import shutil
os.makedirs('/content/drive/MyDrive/data/models', exist_ok=True)
shutil.copytree('models_saved/distilbert_model', '/content/drive/MyDrive/data/models/distilbert_model', dirs_exist_ok=True)
print("✅ DistilBERT backed up to Drive")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-multilingual-cased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.291927695274353, 'eval_accuracy': 0.9034930350358801, 'eval_f1': 0.9030190023280531, 'eval_precision': 0.9037067792794421, 'eval_recall': 0.9025290668564521}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ DistilBERT backed up to Drive

In [ ]:
# DistilBERT: per-language breakdown on bilingual test set
distilbert_en_preds, _ = evaluate_on_texts(distilbert_tokenizer, distilbert_model, en_test_texts_from_bilingual,
                                             en_test_labels_from_bilingual, "DistilBERT — Bilingual test: English subset")
distilbert_es_preds, _ = evaluate_on_texts(distilbert_tokenizer, distilbert_model, es_test_texts_from_bilingual,
                                             es_test_labels_from_bilingual, "DistilBERT — Bilingual test: Spanish subset")

=======================================================
  DistilBERT — Bilingual test: English subset
=======================================================
   Accuracy:  0.9156
   Precision: 0.9171
   Recall:    0.9128
   F1-Score:  0.9145
                 precision    recall  f1-score   support

Non-Abusive (0)       0.93      0.88      0.90      4938
    Abusive (1)       0.91      0.94      0.92      5938

       accuracy                           0.92     10876
      macro avg       0.92      0.91      0.91     10876
   weighted avg       0.92      0.92      0.92     10876

=======================================================
  DistilBERT — Bilingual test: Spanish subset
=======================================================
   Accuracy:  0.8872
   Precision: 0.8872
   Recall:    0.8873
   F1-Score:  0.8872
                 precision    recall  f1-score   support

Non-Abusive (0)       0.88      0.89      0.89      3974
    Abusive (1)       0.89      0.88      0.89      4102

       accuracy                           0.89      8076
      macro avg       0.89      0.89      0.89      8076
   weighted avg       0.89      0.89      0.89      8076

In [ ]:
# ==================== DistilBERT: EN->ES cross-lingual ================================
distilbert_en_tokenizer = AutoTokenizer.from_pretrained('distilbert-base-multilingual-cased')
distilbert_en_model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-multilingual-cased', num_labels=2)

distilbert_en_train_encodings = distilbert_en_tokenizer(english_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
distilbert_en_val_encodings = distilbert_en_tokenizer(english_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

distilbert_en_train_dataset = CyberbullyingDataset(distilbert_en_train_encodings, english_train_labels)
distilbert_en_val_dataset = CyberbullyingDataset(distilbert_en_val_encodings, english_validation_labels)

training_args_en = TrainingArguments(
    output_dir='./results/distilbert_en',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_en = Trainer(
    model=distilbert_en_model,
    args=training_args_en,
    train_dataset=distilbert_en_train_dataset,
    eval_dataset=distilbert_en_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_en.train()

distilbert_en_es_preds, _ = evaluate_on_texts(distilbert_en_tokenizer, distilbert_en_model, spanish_test_texts,
                                                spanish_test_labels, "DistilBERT — EN→ES cross-lingual (train EN, test ES)")

In [ ]:
# ==================== DistilBERT: ES->EN cross-lingual ================================
distilbert_es_tokenizer = AutoTokenizer.from_pretrained('distilbert-base-multilingual-cased')
distilbert_es_model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-multilingual-cased', num_labels=2)

distilbert_es_train_encodings = distilbert_es_tokenizer(spanish_train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
distilbert_es_val_encodings = distilbert_es_tokenizer(spanish_validation_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')

distilbert_es_train_dataset = CyberbullyingDataset(distilbert_es_train_encodings, spanish_train_labels)
distilbert_es_val_dataset = CyberbullyingDataset(distilbert_es_val_encodings, spanish_validation_labels)

training_args_es = TrainingArguments(
    output_dir='./results/distilbert_es',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_steps=500,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
)

trainer_es = Trainer(
    model=distilbert_es_model,
    args=training_args_es,
    train_dataset=distilbert_es_train_dataset,
    eval_dataset=distilbert_es_val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer_es.train()

distilbert_es_en_preds, _ = evaluate_on_texts(distilbert_es_tokenizer, distilbert_es_model, english_test_texts,
                                                english_test_labels, "DistilBERT — ES→EN cross-lingual (train ES, test EN)")

Compare all three transformers (bilingual setting)

In [ ]:
#COLLECTING RESULTS FROM MODELS
all_results = {}

all_results['XLM-R'] = {
    'test_results': xlmr_test_results,
    'predictions': xlmr_pred_labels,
    'probabilities': xlmr_pred_probs,
    'model': xlmr_model,
    'tokenizer': xlmr_tokenizer
}

all_results['DistilBERT'] = {
     'test_results': distilbert_test_results,
     'predictions': distilbert_pred_labels,
     'probabilities': distilbert_pred_probs,
     'model': distilbert_model,
     'tokenizer': distilbert_tokenizer
}

all_results['mBERT'] = {
     'test_results': mbert_test_results,
     'predictions': mbert_pred_labels,
     'probabilities': mbert_pred_probs,
     'model': mbert_model,
     'tokenizer': mbert_tokenizer
}

In [ ]:
# COMPARING METRICS FROM ALL 3 MODELS

comparison_data = []
for name, result in all_results.items():
    comparison_data.append({
        'Model': name,
        'Accuracy': result['test_results']['eval_accuracy'],
        'Precision': result['test_results']['eval_precision'],
        'Recall': result['test_results']['eval_recall'],
        'F1-Score': result['test_results']['eval_f1']
    })

comparison_df = pd.DataFrame(comparison_data)
comparison_df = comparison_df.sort_values('F1-Score', ascending=False)

os.makedirs('reports/results', exist_ok=True)
comparison_df.to_csv('reports/results/transformer_model_comparison.csv', index=False)
print(comparison_df)

In [ ]:
# VISUALIZATION

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
ax = axes[0]
bars = ax.bar(comparison_df['Model'], comparison_df['F1-Score'], color=['#2ecc71', '#3498db', '#e74c3c'])
ax.set_title('Model Comparison: Macro F1-Score', fontsize=14, fontweight='bold')
ax.set_ylabel('Macro F1-Score')
ax.set_ylim(0, 1)
for bar, score in zip(bars, comparison_df['F1-Score']):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'{score:.3f}', ha='center')


# Heatmap
ax = axes[1]
metrics_df = comparison_df.set_index('Model')[['Accuracy', 'Precision', 'Recall', 'F1-Score']]
sns.heatmap(metrics_df, annot=True, fmt='.3f', cmap='RdYlGn', vmin=0.7, vmax=0.95, ax=ax)
ax.set_title('All Metrics Comparison', fontsize=14, fontweight='bold')

plt.tight_layout()
os.makedirs('reports/figures', exist_ok=True)
plt.savefig('reports/figures/model_comparison.png', dpi=300)
plt.show()

In [ ]:
# CONFUSION MATRIX FOR EACH MODEL
from sklearn.metrics import confusion_matrix

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

for idx, (name, result) in enumerate(all_results.items()):
    ax = axes[idx]
    cm = confusion_matrix(test_labels, result['predictions'])
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Non-Abusive', 'Abusive'],
                yticklabels=['Non-Abusive', 'Abusive'])
    ax.set_title(f'{name}', fontsize=12, fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')

plt.suptitle('Confusion Matrices — Bilingual Test Set', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('reports/figures/transformer_confusion_matrices.png', dpi=300)
plt.show()

In [ ]:
# SAVE PREDICTIONS AND PROBABILITIES FOR ENSEMBLE
# FIX: now saves probabilities too (needed for soft-voting ensemble in Notebook 6)
os.makedirs('models_saved', exist_ok=True)
os.makedirs('/content/drive/MyDrive/data/models', exist_ok=True)

for name, result in all_results.items():
    np.save(f'models_saved/{name}_test_predictions.npy', result['predictions'])
    np.save(f'models_saved/{name}_test_probabilities.npy', result['probabilities'])
    # backup to drive
    np.save(f'/content/drive/MyDrive/data/models/{name}_test_predictions.npy', result['predictions'])
    np.save(f'/content/drive/MyDrive/data/models/{name}_test_probabilities.npy', result['probabilities'])

print("✅ Predictions and probabilities saved (local + Drive):")
for name in all_results.keys():
    print(f"   - {name}_test_predictions.npy")
    print(f"   - {name}_test_probabilities.npy")