# Notebook 8: Weighted Cross-Lingual Runs (Bias Flip Mitigation)
Class-weighted loss is applied to all 3 transformer cross-lingual conditions.
The weight direction flips depending on transfer direction:
- EN→ES: weight [1.0, 2.0] — penalise missing Abusive class (low recall in unweighted EN→ES)
- ES→EN: weight [2.0, 1.0] — penalise missing Non-Abusive class (low recall in unweighted ES→EN)

Compare results against unweighted cross-lingual runs to measure bias flip mitigation.

In [1]:
import subprocess, os, sys

GITHUB_USER  = "YusrahS"
GITHUB_REPO  = "Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"
GITHUB_TOKEN = "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"
repo_path    = f"/content/{GITHUB_REPO}"

if not os.path.exists(repo_path):
    subprocess.run(
        f"git clone https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git",
        shell=True, cwd="/content"
    )
    print("✅ Repo cloned")

sys.path.insert(0, repo_path)
os.chdir(repo_path)
print(f"✅ Ready! Working directory: {os.getcwd()}")

✅ Repo cloned
✅ Ready! Working directory: /content/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-

In [2]:
from google.colab import drive
drive.mount('/content/drive') ### using account b

import os
REPO = "Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"
if not os.path.exists(f'/content/drive/MyDrive/{REPO}'):
    !cd /content/drive/MyDrive/ && git clone https://github.com/YusrahS/{REPO}
else:
    !cd /content/drive/MyDrive/{REPO} && git pull

!ln -sf /content/drive/MyDrive/{REPO} /content/{REPO}
%cd /content/{REPO}

DRIVE      = '/content/drive/MyDrive'
MODELS_DIR = '/content/drive/MyDrive/data/models'
DATA_DIR   = '/content/drive/MyDrive/data'
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs('reports/results', exist_ok=True)
print(f"✅ Drive mounted. Models dir: {MODELS_DIR}")

Mounted at /content/drive
Already up to date.
/content
✅ Drive mounted. Models dir: /content/drive/MyDrive/data/models

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
REPO = "Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-"
if not os.path.exists(f'/content/drive/MyDrive/{REPO}'):
    !cd /content/drive/MyDrive/ && git clone https://github.com/YusrahS/{REPO}
else:
    !cd /content/drive/MyDrive/{REPO} && git pull

!ln -sf /content/drive/MyDrive/{REPO} /content/{REPO}
%cd /content/{REPO}

DRIVE      = f'/content/drive/MyDrive/{REPO}'
MODELS_DIR = f'{DRIVE}/data/models'
DATA_DIR   = f'{DRIVE}/data'
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs('reports/results', exist_ok=True)
print(f"✅ Drive mounted. Models dir: {MODELS_DIR}")

Mounted at /content/drive
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 10), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (16/16), 281.32 KiB | 375.00 KiB/s, done.
From https://github.com/YusrahS/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-
   50b6b63..02fcc47  main       -> origin/main
Updating 50b6b63..02fcc47
Fast-forward
 Notebooks/Notebook_5_Transformers.ipynb            | 15679 +++++++++++++++++--
 .../Notebook_5b_CrossLingual_and_Predictions.ipynb |  1926 +++
 Notebooks/Notebook_6_Ensemble (1).ipynb            |   803 +
 Notebooks/Notebook_7_BETO (1).ipynb                |  5337 +++++++
 4 files changed, 22489 insertions(+), 1256 deletions(-)
 create mode 100644 Notebooks/Notebook_5b_CrossLingual_and_Predictions.ipynb
 create mode 100644 Notebooks/Notebook_6_Ensemble (1).ipynb
 create mode 100644 Notebooks/Notebook_7_BETO (1).ipynb
/content
✅ Drive mounted. Models dir: /content/drive/MyDrive/Cyberbullying-Detection-in-Bilingual-English-Spanish-Text-A-Comparative-Study-/data/models

In [3]:
import pandas as pd
import numpy as np
import pickle
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
)
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report,
)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print("✅ Imports done")

✅ Imports done

In [4]:
# Load English and Spanish transformer data
with open(f'{DATA_DIR}/english_transformer_data.pkl', 'rb') as f:
    english_data = pickle.load(f)

with open(f'{DATA_DIR}/spanish_transformer_data.pkl', 'rb') as f:
    spanish_data = pickle.load(f)

english_train_texts       = english_data['train_texts']
english_validation_texts  = english_data['val_texts']
english_test_texts        = english_data['test_texts']
english_train_labels      = english_data['train_labels']
english_validation_labels = english_data['val_labels']
english_test_labels       = english_data['test_labels']

spanish_train_texts       = spanish_data['train_texts']
spanish_validation_texts  = spanish_data['val_texts']
spanish_test_texts        = spanish_data['test_texts']
spanish_train_labels      = spanish_data['train_labels']
spanish_validation_labels = spanish_data['val_labels']
spanish_test_labels       = spanish_data['test_labels']

print(f"English train: {len(english_train_texts)} | English test: {len(english_test_texts)}")
print(f"Spanish train: {len(spanish_train_texts)} | Spanish test: {len(spanish_test_texts)}")
print("✅ Data loaded")

English train: 50756 | English test: 10876
Spanish train: 37687 | Spanish test: 8076
✅ Data loaded

In [5]:
class CyberbullyingDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels
    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)


def make_weighted_trainer(class_weights):
    """Returns a Trainer subclass that uses weighted cross-entropy loss.
    class_weights: list of 2 floats e.g. [1.0, 2.0]
    """
    weight_tensor = torch.tensor(class_weights, dtype=torch.float)

    class WeightedTrainer(Trainer):
        def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
            labels  = inputs.get("labels")
            outputs = model(**inputs)
            logits  = outputs.get("logits")
            device  = logits.device
            loss_fn = nn.CrossEntropyLoss(weight=weight_tensor.to(device))
            loss    = loss_fn(logits, labels)
            return (loss, outputs) if return_outputs else loss

    return WeightedTrainer


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {
        'accuracy':  accuracy_score(labels, predictions),
        'f1':        f1_score(labels, predictions, average='macro'),
        'precision': precision_score(labels, predictions, average='macro'),
        'recall':    recall_score(labels, predictions, average='macro'),
    }


def get_training_args(output_dir):
    return TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=3,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        warmup_steps=500,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
    )


def run_weighted_cross_lingual(model_name, hf_checkpoint,
                                train_texts, train_labels,
                                val_texts,   val_labels,
                                test_texts,  test_labels,
                                direction, class_weights, output_dir):
    """Train with class-weighted loss, evaluate cross-lingually."""
    print(f"\n{'='*65}")
    print(f"  {model_name} — {direction}  [weights: {class_weights}]")
    print(f"{'='*65}")

    tokenizer = AutoTokenizer.from_pretrained(hf_checkpoint)
    model     = AutoModelForSequenceClassification.from_pretrained(hf_checkpoint, num_labels=2)

    train_enc = tokenizer(train_texts, truncation=True, padding=True, max_length=128, return_tensors='pt')
    val_enc   = tokenizer(val_texts,   truncation=True, padding=True, max_length=128, return_tensors='pt')
    test_enc  = tokenizer(test_texts,  truncation=True, padding=True, max_length=128, return_tensors='pt')

    WeightedTrainer = make_weighted_trainer(class_weights)

    trainer = WeightedTrainer(
        model=model,
        args=get_training_args(output_dir),
        train_dataset=CyberbullyingDataset(train_enc, train_labels),
        eval_dataset=CyberbullyingDataset(val_enc, val_labels),
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )
    trainer.train()

    output      = trainer.predict(CyberbullyingDataset(test_enc, test_labels))
    preds       = np.argmax(output.predictions, axis=1)
    macro_f1    = f1_score(test_labels, preds, average='macro')
    abusive_rec = recall_score(test_labels, preds, pos_label=1)
    non_ab_rec  = recall_score(test_labels, preds, pos_label=0)

    print(f"\n  Accuracy:          {accuracy_score(test_labels, preds):.4f}")
    print(f"  Macro Precision:   {precision_score(test_labels, preds, average='macro'):.4f}")
    print(f"  Macro Recall:      {recall_score(test_labels, preds, average='macro'):.4f}")
    print(f"  Macro F1:          {macro_f1:.4f}")
    print(f"  Abusive Recall:    {abusive_rec:.4f}  ← key metric for EN→ES")
    print(f"  Non-Abusive Recall:{non_ab_rec:.4f}  ← key metric for ES→EN")
    print(classification_report(test_labels, preds, target_names=['Non-Abusive', 'Abusive']))

    return preds, macro_f1, abusive_rec, non_ab_rec

print("✅ WeightedTrainer and helpers ready")

✅ WeightedTrainer and helpers ready

In [6]:
from IPython.display import display, Javascript
display(Javascript("""
    function ClickConnect(){
        document.querySelector("colab-connect-button").click()
    }
    setInterval(ClickConnect, 60000)
"""))
print("✅ Keep-alive enabled")

✅ Keep-alive enabled

## Results storage
All weighted results are collected here for the final comparison table.

In [7]:
# Unweighted results from Notebook 5b (for comparison)
unweighted = {
    'DistilBERT': {'EN_ES': {'f1': 0.4294, 'abusive_rec': 0.17, 'non_ab_rec': 0.81},
                   'ES_EN': {'f1': 0.4443, 'abusive_rec': 0.77, 'non_ab_rec': 0.19}},
    'mBERT':      {'EN_ES': {'f1': 0.3903, 'abusive_rec': 0.10, 'non_ab_rec': 0.87},
                   'ES_EN': {'f1': 0.4548, 'abusive_rec': 0.71, 'non_ab_rec': 0.24}},
    'XLM-R':      {'EN_ES': {'f1': 0.4950, 'abusive_rec': 0.34, 'non_ab_rec': 0.68},
                   'ES_EN': {'f1': 0.4271, 'abusive_rec': 0.55, 'non_ab_rec': 0.31}},
}
weighted = {}
print("✅ Unweighted baseline results loaded")

✅ Unweighted baseline results loaded

## PART 1: DistilBERT — EN→ES weighted
Weight [1.0, 2.0]: penalise missing Abusive class (currently only 17% recall)

In [ ]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'DistilBERT',
    hf_checkpoint  = 'distilbert-base-multilingual-cased',
    train_texts    = english_train_texts,
    train_labels   = english_train_labels,
    val_texts      = english_validation_texts,
    val_labels     = english_validation_labels,
    test_texts     = spanish_test_texts,
    test_labels    = spanish_test_labels,
    direction      = 'EN→ES weighted',
    class_weights  = [1.0, 2.0],
    output_dir     = './results/distilbert_en_es_weighted',
)
np.save(f'{MODELS_DIR}/distilbert_en_es_weighted_preds.npy', preds)
weighted.setdefault('DistilBERT', {})['EN_ES'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ DistilBERT EN→ES weighted predictions saved")

=================================================================
  DistilBERT — EN→ES weighted  [weights: [1.0, 2.0]]
=================================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-multilingual-cased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Accuracy:          0.4881
  Macro Precision:   0.4889
  Macro Recall:      0.4928
  Macro F1:          0.4411
  Abusive Recall:    0.1950  ← key metric for EN→ES
  Non-Abusive Recall:0.7906  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.49      0.79      0.60      3974
     Abusive       0.49      0.20      0.28      4102

    accuracy                           0.49      8076
   macro avg       0.49      0.49      0.44      8076
weighted avg       0.49      0.49      0.44      8076

✅ DistilBERT EN→ES weighted predictions saved

## PART 2: DistilBERT — ES→EN weighted
Weight [2.0, 1.0]: penalise missing Non-Abusive class (currently only 19% recall)

In [ ]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'DistilBERT',
    hf_checkpoint  = 'distilbert-base-multilingual-cased',
    train_texts    = spanish_train_texts,
    train_labels   = spanish_train_labels,
    val_texts      = spanish_validation_texts,
    val_labels     = spanish_validation_labels,
    test_texts     = english_test_texts,
    test_labels    = english_test_labels,
    direction      = 'ES→EN weighted',
    class_weights  = [2.0, 1.0],
    output_dir     = './results/distilbert_es_en_weighted',
)
np.save(f'{MODELS_DIR}/distilbert_es_en_weighted_preds.npy', preds)
weighted['DistilBERT']['ES_EN'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ DistilBERT ES→EN weighted predictions saved")

=================================================================
  DistilBERT — ES→EN weighted  [weights: [2.0, 1.0]]
=================================================================

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-multilingual-cased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Accuracy:          0.4800
  Macro Precision:   0.4451
  Macro Recall:      0.4575
  Macro F1:          0.4333
  Abusive Recall:    0.7026  ← key metric for EN→ES
  Non-Abusive Recall:0.2124  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.37      0.21      0.27      4938
     Abusive       0.52      0.70      0.60      5938

    accuracy                           0.48     10876
   macro avg       0.45      0.46      0.43     10876
weighted avg       0.45      0.48      0.45     10876

✅ DistilBERT ES→EN weighted predictions saved

## PART 3: mBERT — EN→ES weighted
Weight [1.0, 2.0]: penalise missing Abusive class (currently only 10% recall)

In [ ]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'mBERT',
    hf_checkpoint  = 'bert-base-multilingual-cased',
    train_texts    = english_train_texts,
    train_labels   = english_train_labels,
    val_texts      = english_validation_texts,
    val_labels     = english_validation_labels,
    test_texts     = spanish_test_texts,
    test_labels    = spanish_test_labels,
    direction      = 'EN→ES weighted',
    class_weights  = [1.0, 2.0],
    output_dir     = './results/mbert_en_es_weighted',
)
np.save(f'{MODELS_DIR}/mbert_en_es_weighted_preds.npy', preds)
weighted.setdefault('mBERT', {})['EN_ES'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ mBERT EN→ES weighted predictions saved")

=================================================================
  mBERT — EN→ES weighted  [weights: [1.0, 2.0]]
=================================================================

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  Accuracy:          0.4759
  Macro Precision:   0.4549
  Macro Recall:      0.4820
  Macro F1:          0.3877
  Abusive Recall:    0.0948  ← key metric for EN→ES
  Non-Abusive Recall:0.8691  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.48      0.87      0.62      3974
     Abusive       0.43      0.09      0.16      4102

    accuracy                           0.48      8076
   macro avg       0.45      0.48      0.39      8076
weighted avg       0.45      0.48      0.38      8076

✅ mBERT EN→ES weighted predictions saved

## PART 4: mBERT — ES→EN weighted
Weight [2.0, 1.0]: penalise missing Non-Abusive class (currently only 24% recall)

In [ ]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'mBERT',
    hf_checkpoint  = 'bert-base-multilingual-cased',
    train_texts    = spanish_train_texts,
    train_labels   = spanish_train_labels,
    val_texts      = spanish_validation_texts,
    val_labels     = spanish_validation_labels,
    test_texts     = english_test_texts,
    test_labels    = english_test_labels,
    direction      = 'ES→EN weighted',
    class_weights  = [2.0, 1.0],
    output_dir     = './results/mbert_es_en_weighted',
)
np.save(f'{MODELS_DIR}/mbert_es_en_weighted_preds.npy', preds)
weighted['mBERT']['ES_EN'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ mBERT ES→EN weighted predictions saved")

=================================================================
  mBERT — ES→EN weighted  [weights: [2.0, 1.0]]
=================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  Accuracy:          0.4929
  Macro Precision:   0.4746
  Macro Recall:      0.4773
  Macro F1:          0.4686
  Abusive Recall:    0.6472  ← key metric for EN→ES
  Non-Abusive Recall:0.3074  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.42      0.31      0.36      4938
     Abusive       0.53      0.65      0.58      5938

    accuracy                           0.49     10876
   macro avg       0.47      0.48      0.47     10876
weighted avg       0.48      0.49      0.48     10876

✅ mBERT ES→EN weighted predictions saved

## PART 5: XLM-R — EN→ES weighted
Weight [1.0, 2.0]: penalise missing Abusive class (currently 34% recall)

In [ ]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'XLM-R',
    hf_checkpoint  = 'xlm-roberta-base',
    train_texts    = english_train_texts,
    train_labels   = english_train_labels,
    val_texts      = english_validation_texts,
    val_labels     = english_validation_labels,
    test_texts     = spanish_test_texts,
    test_labels    = spanish_test_labels,
    direction      = 'EN→ES weighted',
    class_weights  = [1.0, 2.0],
    output_dir     = './results/xlmr_en_es_weighted',
)
np.save(f'{MODELS_DIR}/xlmr_en_es_weighted_preds.npy', preds)
weighted.setdefault('XLM-R', {})['EN_ES'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ XLM-R EN→ES weighted predictions saved")

=================================================================
  XLM-R — EN→ES weighted  [weights: [1.0, 2.0]]
=================================================================

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Accuracy:          0.5258
  Macro Precision:   0.5310
  Macro Recall:      0.5282
  Macro F1:          0.5159
  Abusive Recall:    0.3769  ← key metric for EN→ES
  Non-Abusive Recall:0.6794  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.51      0.68      0.59      3974
     Abusive       0.55      0.38      0.45      4102

    accuracy                           0.53      8076
   macro avg       0.53      0.53      0.52      8076
weighted avg       0.53      0.53      0.51      8076

✅ XLM-R EN→ES weighted predictions saved

## PART 6: XLM-R — ES→EN weighted
Weight [2.0, 1.0]: penalise missing Non-Abusive class (currently 31% recall)

In [8]:
preds, f1, ab_rec, nab_rec = run_weighted_cross_lingual(
    model_name     = 'XLM-R',
    hf_checkpoint  = 'xlm-roberta-base',
    train_texts    = spanish_train_texts,
    train_labels   = spanish_train_labels,
    val_texts      = spanish_validation_texts,
    val_labels     = spanish_validation_labels,
    test_texts     = english_test_texts,
    test_labels    = english_test_labels,
    direction      = 'ES→EN weighted',
    class_weights  = [2.0, 1.0],
    output_dir     = './results/xlmr_es_en_weighted',
)
np.save(f'{MODELS_DIR}/xlmr_es_en_weighted_preds.npy', preds)
weighted['XLM-R']['ES_EN'] = {'f1': f1, 'abusive_rec': ab_rec, 'non_ab_rec': nab_rec}
print("✅ XLM-R ES→EN weighted predictions saved")

=================================================================
  XLM-R — ES→EN weighted  [weights: [2.0, 1.0]]
=================================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Accuracy:          0.4314
  Macro Precision:   0.4232
  Macro Recall:      0.4241
  Macro F1:          0.4234
  Abusive Recall:    0.5032  ← key metric for EN→ES
  Non-Abusive Recall:0.3451  ← key metric for ES→EN
              precision    recall  f1-score   support

 Non-Abusive       0.37      0.35      0.36      4938
     Abusive       0.48      0.50      0.49      5938

    accuracy                           0.43     10876
   macro avg       0.42      0.42      0.42     10876
weighted avg       0.43      0.43      0.43     10876

KeyError: 'XLM-R'

## PART 7: Before vs After Comparison Table (Bias Flip Mitigation)

In [ ]:
rows = []
for model in ['DistilBERT', 'mBERT', 'XLM-R']:
    for direction, label in [('EN_ES', 'EN→ES'), ('ES_EN', 'ES→EN')]:
        u = unweighted[model][direction]
        w = weighted[model][direction]

        # For EN->ES, key metric is Abusive recall
        # For ES->EN, key metric is Non-Abusive recall
        key_before = u['abusive_rec'] if direction == 'EN_ES' else u['non_ab_rec']
        key_after  = w['abusive_rec'] if direction == 'EN_ES' else w['non_ab_rec']
        key_label  = 'Abusive Recall' if direction == 'EN_ES' else 'Non-Abusive Recall'

        rows.append({
            'Model':       model,
            'Direction':   label,
            'F1 Before':   f"{u['f1']:.3f}",
            'F1 After':    f"{w['f1']:.3f}",
            'F1 Change':   f"{(w['f1'] - u['f1'])*100:+.1f}pp",
            key_label + ' Before': f"{key_before:.0%}",
            key_label + ' After':  f"{key_after:.0%}",
            'Recall Change': f"{(key_after - key_before)*100:+.1f}pp",
        })

comparison_df = pd.DataFrame(rows)
print("\n── Bias Flip Mitigation: Weighted vs Unweighted Cross-Lingual Results ──")
print(comparison_df.to_string(index=False))

comparison_df.to_csv(f'{MODELS_DIR}/weighted_vs_unweighted_comparison.csv', index=False)
comparison_df.to_csv('reports/results/weighted_vs_unweighted_comparison.csv', index=False)
print("\n✅ Comparison table saved")

In [ ]:
# Bar chart comparing F1 before and after weighting for each model/direction
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

models = ['DistilBERT', 'mBERT', 'XLM-R']
x = np.arange(len(models))
width = 0.35

for ax_idx, (direction, label, key) in enumerate([
    ('EN_ES', 'EN→ES', 'abusive_rec'),
    ('ES_EN', 'ES→EN', 'non_ab_rec'),
]):
    ax = axes[ax_idx]
    before = [unweighted[m][direction]['f1'] for m in models]
    after  = [weighted[m][direction]['f1'] for m in models]

    bars1 = ax.bar(x - width/2, before, width, label='Unweighted', color='#90CAF9', edgecolor='white')
    bars2 = ax.bar(x + width/2, after,  width, label='Weighted',   color='#1565C0', edgecolor='white')

    ax.set_title(f'{label} Cross-Lingual: Weighted vs Unweighted F1',
                 fontsize=12, fontweight='bold')
    ax.set_ylabel('Macro F1-Score')
    ax.set_ylim(0.2, 0.7)
    ax.set_xticks(x)
    ax.set_xticklabels(models)
    ax.legend()

    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=8)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{bar.get_height():.3f}', ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.savefig('reports/figures/weighted_vs_unweighted_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print("✅ Comparison chart saved")

## Summary

In [ ]:
print("\n" + "="*65)
print("  WEIGHTED CROSS-LINGUAL RESULTS SUMMARY")
print("="*65)
print("\nEN→ES (key metric: Abusive Recall — was very low in unweighted):")
for m in ['DistilBERT', 'mBERT', 'XLM-R']:
    u = unweighted[m]['EN_ES']
    w = weighted[m]['EN_ES']
    print(f"  {m:12s}  F1: {u['f1']:.3f}→{w['f1']:.3f} ({(w['f1']-u['f1'])*100:+.1f}pp)  "
          f"Abusive Recall: {u['abusive_rec']:.0%}→{w['abusive_rec']:.0%}")

print("\nES→EN (key metric: Non-Abusive Recall — was very low in unweighted):")
for m in ['DistilBERT', 'mBERT', 'XLM-R']:
    u = unweighted[m]['ES_EN']
    w = weighted[m]['ES_EN']
    print(f"  {m:12s}  F1: {u['f1']:.3f}→{w['f1']:.3f} ({(w['f1']-u['f1'])*100:+.1f}pp)  "
          f"Non-Ab Recall:  {u['non_ab_rec']:.0%}→{w['non_ab_rec']:.0%}")

print("\n✅ All 6 weighted cross-lingual runs complete")
print("✅ Results saved to Drive and reports/results/")
print("\nNext: Error analysis (Notebook 9) or LoRA+LLM (Notebook 9)")

In [9]:
import os
MODELS_DIR = '/content/drive/MyDrive/data/models'
files = [
    'distilbert_en_es_weighted_preds.npy',
    'distilbert_es_en_weighted_preds.npy',
    'mbert_en_es_weighted_preds.npy',
    'mbert_es_en_weighted_preds.npy',
    'xlmr_en_es_weighted_preds.npy',
    'xlmr_es_en_weighted_preds.npy',
]
for f in files:
    exists = os.path.exists(f'{MODELS_DIR}/{f}')
    print(f"{'✅' if exists else '❌'} {f}")

✅ distilbert_en_es_weighted_preds.npy
✅ distilbert_es_en_weighted_preds.npy
✅ mbert_en_es_weighted_preds.npy
✅ mbert_es_en_weighted_preds.npy
✅ xlmr_en_es_weighted_preds.npy
✅ xlmr_es_en_weighted_preds.npy